//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMSforAKF.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-A6GPOLU\\SQLEXPRESS;Initial Catalog=\"C:\\USERS\\USER\\SOURCE\\REPO" +
            "S\\WEBAPP\\ANIMAL MANAGEMENT SYSTEM\\DATABASEAKF.MDF\";Integrated Security=True;Encr" +
            "ypt=True;TrustServerCertificate=True")]
        public string C__USERS_USER_SOURCE_REPOS_WEBAPP_ANIMAL_MANAGEMENT_SYSTEM_DATABASEAKF_MDFConnectionString {
            get {
                return ((string)(this["C__USERS_USER_SOURCE_REPOS_WEBAPP_ANIMAL_MANAGEMENT_SYSTEM_DATABASEAKF_MDFConnect" +
                    "ionString"]));
            }
        }
    }
}
